package Parsing;

import java.awt.Color;
import java.io.File;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JTextArea;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Highlighter.HighlightPainter;

public class PruebaAnalex extends javax.swing.JFrame {
    private ErrorMgr errorMgr;
    private Analex analex;
    
    public PruebaAnalex() {
        initComponents();
        
        errorMgr = new ErrorMgr();
        analex   = new Analex(errorMgr);
        
        setEventosModificacion(textArea);
        onModificacion();
    }

//----------------------------------
    private void resaltar(int pos, int longitud){
        desResaltar();
        HighlightPainter colorResaltado = new DefaultHighlighter.DefaultHighlightPainter(Color.pink);
        
        try {
           textArea.getHighlighter().addHighlight(pos, pos+longitud, colorResaltado); 
        } catch (Exception e) {}
        
        textArea.setSelectionStart(pos);
        textArea.setSelectionEnd(pos + longitud);
    }
    
    private void desResaltar(){
        textArea.getHighlighter().removeAllHighlights();
    }
//----------------------------------
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEjemplo = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        labelError = new java.awt.Label();
        labelPreanalisis = new javax.swing.JLabel();
        labelLexema = new javax.swing.JLabel();
        btnAvanzar = new javax.swing.JButton();
        btnInit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(57, 62, 70));

        btnEjemplo.setBackground(new java.awt.Color(45, 125, 207));
        btnEjemplo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEjemplo.setForeground(new java.awt.Color(255, 255, 255));
        btnEjemplo.setText("Cargar Ejemplo");
        btnEjemplo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEjemploMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEjemploMouseExited(evt);
            }
        });
        btnEjemplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjemploActionPerformed(evt);
            }
        });

        btnAbrir.setBackground(new java.awt.Color(45, 125, 207));
        btnAbrir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAbrir.setForeground(new java.awt.Color(255, 255, 255));
        btnAbrir.setText("Abrir..");
        btnAbrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAbrirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAbrirMouseExited(evt);
            }
        });
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });

        textArea.setBackground(new java.awt.Color(237, 237, 237));
        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        labelError.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelError.setForeground(new java.awt.Color(216, 40, 50));
        labelError.setText("labelError");

        labelPreanalisis.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelPreanalisis.setForeground(new java.awt.Color(255, 255, 255));
        labelPreanalisis.setText("labelPreanalisis");

        labelLexema.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelLexema.setForeground(new java.awt.Color(255, 255, 255));
        labelLexema.setText("labelLexema");

        btnAvanzar.setBackground(new java.awt.Color(45, 125, 207));
        btnAvanzar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAvanzar.setForeground(new java.awt.Color(255, 255, 255));
        btnAvanzar.setText("Analex.Avanzar( );");
        btnAvanzar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAvanzarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAvanzarMouseExited(evt);
            }
        });
        btnAvanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvanzarActionPerformed(evt);
            }
        });

        btnInit.setBackground(new java.awt.Color(45, 125, 207));
        btnInit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInit.setForeground(new java.awt.Color(255, 255, 255));
        btnInit.setText("Analex.Init( );");
        btnInit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInitMouseExited(evt);
            }
        });
        btnInit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnEjemplo)
                                .addGap(30, 30, 30)
                                .addComponent(btnAbrir))
                            .addComponent(labelError, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnAvanzar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnInit, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelLexema, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPreanalisis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEjemplo)
                    .addComponent(btnAbrir))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnInit)
                        .addGap(44, 44, 44)
                        .addComponent(btnAvanzar)
                        .addGap(41, 41, 41)
                        .addComponent(labelLexema)
                        .addGap(41, 41, 41)
                        .addComponent(labelPreanalisis))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnAvanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvanzarActionPerformed
            //Se hizo click en el botón [Avanzar]
        analex.avanzar();
        mostrarResults();
    }//GEN-LAST:event_btnAvanzarActionPerformed

    private void btnInitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInitActionPerformed
        //Se hizo click en el botón [Init]
        analex.init( textArea.getText() );
        btnAvanzar.setEnabled(true);
        mostrarResults();
    }//GEN-LAST:event_btnInitActionPerformed

    private void btnEjemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjemploActionPerformed
        String progFuente = 
                "(* En este ejemplo, se exhiben todos los tokens del lenguaje.\n" +
                "   Recuerde que el lenguaje NO es case-sensitive *)\n\n" +
                "       //Palabras reservadas\n" +
                "PROGRAM Var PROCEDURE Begin End if THEN ELSE FOR TO DO DOWNTO\n" + 
                "WHILE REPEAT UNTIL\n" +
                "READLN WRITELN \n" +
                "\n" +
                "	//Símbolos y operadores\n" +
                ", :  ; ( ) := .\n" +
                "NOT AND OR + - *  MOD % DIV /\n" +
                "\n" +
                "	//NUM, ID y STRINGctte\n" +
                "1234 id2 \"String constante\" \n" +
                "\n" +
                "       {OPREL y TIPO}\n" +
                "< <= <> > >= = \n" +
                "integer boolean";
        
        textArea.setText(progFuente);
    }//GEN-LAST:event_btnEjemploActionPerformed

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        JFileChooser fileChooser = new JFileChooser(".");
        fileChooser.showOpenDialog(this);
        
        try{
            File f = fileChooser.getSelectedFile();
            if (f==null)
                return;
            
            Scanner scn;       
            scn = new Scanner(f);
            String s="";
            while (scn.hasNext())
                s += scn.nextLine() + "\n";                
            
            textArea.setText(s);
            textArea.setCaretPosition(0);
        }catch(Exception e) {};
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void btnEjemploMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEjemploMouseEntered
        // TODO add your handling code here:
        btnEjemplo.setBackground(new Color(38,102,207));
    }//GEN-LAST:event_btnEjemploMouseEntered

    private void btnAbrirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbrirMouseEntered
        // TODO add your handling code here:
        btnAbrir.setBackground(new Color(38,102,207));
    }//GEN-LAST:event_btnAbrirMouseEntered

    private void btnInitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInitMouseEntered
        // TODO add your handling code here:
        btnInit.setBackground(new Color(38,102,207));
    }//GEN-LAST:event_btnInitMouseEntered

    private void btnAvanzarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAvanzarMouseEntered
        // TODO add your handling code here:
        btnAvanzar.setBackground(new Color(38,102,207));
    }//GEN-LAST:event_btnAvanzarMouseEntered

    private void btnEjemploMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEjemploMouseExited
        // TODO add your handling code here:
        btnEjemplo.setBackground(new Color(45,125,207));
    }//GEN-LAST:event_btnEjemploMouseExited

    private void btnAbrirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbrirMouseExited
        // TODO add your handling code here:
        btnAbrir.setBackground(new Color(45,125,207));
    }//GEN-LAST:event_btnAbrirMouseExited

    private void btnInitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInitMouseExited
        // TODO add your handling code here:
        btnInit.setBackground(new Color(45,125,207));
    }//GEN-LAST:event_btnInitMouseExited

    private void btnAvanzarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAvanzarMouseExited
        // TODO add your handling code here:
        btnAvanzar.setBackground(new Color(45,125,207));
    }//GEN-LAST:event_btnAvanzarMouseExited

    private void mostrarResults(){
        labelLexema.setText("Lexema: "+analex.lexema());
        labelPreanalisis.setText("Preanalisis: "+analex.preanalisis());
        resaltar(analex.getPosLexema(), analex.lexema().length());
        
        if (errorMgr.hayError()){
            labelError.setText("Error: "+errorMgr.getErrorMsj());
            btnAvanzar.setEnabled(false);
        }
    }
    
    private void setEventosModificacion(JTextArea textArea){
        textArea.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void removeUpdate(DocumentEvent e) {
                onModificacion();
            }

            @Override
            public void insertUpdate(DocumentEvent e) {
                onModificacion();
            }

            @Override
            public void changedUpdate(DocumentEvent arg0) {
                onModificacion();
            }
        });
    }
    
    private void onModificacion(){
        labelLexema.setText("");
        labelPreanalisis.setText("");
        labelError.setText("");
        btnAvanzar.setEnabled(false);
        desResaltar();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PruebaAnalex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PruebaAnalex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PruebaAnalex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PruebaAnalex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                PruebaAnalex form = new PruebaAnalex();
                //new Interfaz().setVisible(true);
                form.setLocationRelativeTo(null);  //Centrar el form
                form.setVisible(true);
            }
        });     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnAvanzar;
    private javax.swing.JButton btnEjemplo;
    private javax.swing.JButton btnInit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label labelError;
    private javax.swing.JLabel labelLexema;
    private javax.swing.JLabel labelPreanalisis;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
